config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :user_stocks, except: [:show, :edit, :update]

  root 'welcome#index'

  #USER ROUTES
  get 'my_portfolio', to: 'users#my_portfolio'
  ############

  #STOCK ROUTES
  get 'search_stocks', to: 'stocks#search'
  #############

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord

  has_many :user_stocks
  has_many :users, through: :user_stocks

  #Functions needed to work with stocks. These are all static methods.

  #Looks into the db to try to find a stock by a ticker. This is so we don't have to look up the stock through the web service every time
  #The db and model association allows us to simply use where() because the model knows it is bound to the stocks db table
  def self.find_stock_in_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

  #Look up a stock. If it does not exist, return nil
  def self.find_stock_by_service(ticker_symbol)
    looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
    return nil unless looked_up_stock.name

    #Create a new stock object if we pass the above test (stock not being nil)
    new_stock = new(ticker: looked_up_stock.symbol, name: looked_up_stock.name)
    new_stock.last_price = new_stock.price
    new_stock
  end

  #Gets the price for the relevant stock
  def price

    #If we are able to get the closing price then return it
    closing_price = StockQuote::Stock.quote(ticker).close
    return "#{closing_price} (Closing)" if closing_price

    #Otherwise, we try to get the opening price
    opening_price = StockQuote::Stock.quote(ticker).open
    return "#{opening_price} (Opening)" if opening_price

    #Otherwise, return unavailable
    'Unavailable'

  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  def can_add_stock?(ticker_symbol)
    #You can only add a stock if you're under the stock limit AND the stock you want to track is not already being tracked by the same user
    under_stock_limit? && !stock_already_added?(ticker_symbol)
  end

  def under_stock_limit?
    #This references the specific user (the db record) so don't be surprised
    (user_stocks.count <= 10)
  end

  def stock_already_added?(ticker_symbol)
     stock = Stock.find_by_ticker(ticker_symbol)
     return false unless stock
     user_stocks.where(stock_id: stock.id).exists?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #Before any action by this controller is executed, we MUST have a logged in user.
  before_action :authenticate_user!


end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock]
      #Attemps to first set the stock to the one in the db
      @stock = Stock.find_stock_in_db(params[:stock])
      #If the stock is not found, look up the stock through the service and set it
      @stock ||= Stock.find_stock_by_service(params[:stock])
    end

    if @stock
      #render json: @stock
      render partial: 'lookup'
    else
      render status: :not_found, nothing: true
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_portfolio

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_spinner.html.erb
<div id="spinner" class="row col-md-12 text-center spinner" style="display: none;">
  <i class="fa fa-spinner fa-spin fa-2x"></i> Processing...
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "JCStocks" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">JCStocks</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/stocks/_lookup.html.erb
<div id="stock-lookup">

  <h3>Search for Stocks</h3>

  <!--Here we use a form_tag a form_for is for a specific model. This is just a basic form so we use form_tag-->
  <!--Additionally, this request will be done by AJAX; this means we have to supply: remote: true, method: :get, id:-->
  <!--The id is needed for us to use with javascript later-->
  <%= form_tag search_stocks_path, remote: true, method: :get, id: 'stock-lookup-form' do %>
      <div class="form-group text-center col-md-12">
        <div class="col-md-10">
          <%= text_field_tag :stock, params[:stock], placeholder: 'Stock ticker symbol', autofocus: true, class: 'form-control search-box input-lg' %>
        </div>
        <div class="col-md-2">
          <%= button_tag(type: :submit, class: 'btn btn-lg btn-success') do %>
              <i class="fa fa-search"></i> Look up a stock
          <% end %>
        </div>
      </div>
  <% end %>
  <%= render 'common/spinner' %>
  <!--The stock successfully got created -->
  <% if @stock %>
      <div id="stock-lookup-results" class="well results-block">
        <strong>Symbol:</strong> <%= @stock.ticker %>
        <strong>Name:</strong> <%= @stock.name %>
        <strong>Price:</strong> <%= @stock.price %>
        <% if current_user.can_add_stock?(@stock.ticker) %>
            <%= link_to 'Add to my Stocks', user_stocks_path(user: current_user, stock_ticker: @stock.ticker,
                                                             stock_id: @stock.id ? @stock.id : ''), class: 'btn btn-xs btn-success', method: :post %>
        <% else %>
        <span class="label label-default">Stock cannot be added because you have already added
          <% if !current_user.under_stock_limit? %>
              10 stocks
          <% elsif current_user.stock_already_added?(@stock.ticker) %>
              this stock
          <% end %>
        </span>
        <% end %>
      </div>
  <% end %>
  <div id="stock-lookup-errors"></div>

</div>

app/views/users/my_portfolio.html.erb
<%= render 'stocks/lookup' %>

app/views/welcome/index.html.erb
<h1>Welcome to JC Stocks! First version</h1>

<%= link_to "logout", destroy_user_session_path, method: :delete %>